import random
import sys
import os
from datetime import datetime, timedelta
from faker import Faker
from werkzeug.security import generate_password_hash

# Adjust path to find app and models according to your folder structure
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from app import app, db
from main.models import Users, Student, Company, Drive, Application, Notification

fake = Faker()

def seed_data():
    with app.app_context():
        print("--- Cleaning old data ---")
        db.drop_all()
        db.create_all()
        print("Database tables recreated.")


        print("Creating primary demo accounts...")
        admin_u = Users(username="admin", pass_hash=generate_password_hash("admin"), role="admin", profile_completed=True)
        student_u = Users(username="student", pass_hash=generate_password_hash("student"), role="student", profile_completed=True)
        company_u = Users(username="company", pass_hash=generate_password_hash("company"), role="company", profile_completed=True)
        
        db.session.add_all([admin_u, student_u, company_u])
        db.session.commit()

        demo_student = Student(
            user_id=student_u.id, 
            fname="Harsh", 
            lname="Khandal", 
            roll="2023XXXXXX",
            email="student@demo.com", 
            phone="9876543XXX", 
            cgpa=9.9, 
            graduation_year=2029, 
            degree_field="BS in Data Science",
            batch="2023 - F2", 
            skills="Python, SQL, React, Node.js, AWS, Docker", 
            bio="Data Science enthusiast with a strong foundation in machine learning algorithms and full-stack web development. I love participating in hackathons and building scalable APIs.",
            resume="http://127.0.0.1:5000/static/uploads/resumes/resume.pdf",
            github="https://github.com/demostudent",
            linkedin="https://linkedin.com/in/demostudent",
            portfolio="https://demostudent.dev",
            status="approved"
        )
        
        demo_company = Company(
            user_id=company_u.id, 
            name="Harsh Tech Solutions", 
            industry="AI/ML & Cloud",
            logo="http://127.0.0.1:5000/static/uploads/logos/logo.png",
            short_desc="Innovating the future of cloud-native applications.", 
            description="Demo Tech Solutions is a global leader in AI-driven cloud infrastructure. We specialize in building highly scalable, fault-tolerant enterprise software. Our teams work on cutting-edge machine learning models, big data analytics, and next-generation cybersecurity protocols.",
            location="Bangalore", 
            hr_contact="Jane Doe (HR Manager)", 
            email="careers@demotech.com", 
            employees_count="500-1000",
            website="https://www.demotech.com",
            status="approved"
        )
        
        db.session.add_all([demo_student, demo_company])
        db.session.commit()


        print("🚀 Generating 50+ Students and 50+ Companies with deep profiles...")
        all_students = [demo_student]
        all_companies = [demo_company]

        degree_options = ["B.Tech Computer Science", "BS Data Science", "B.Tech Electrical", "M.Tech AI/ML", "B.Tech IT", "B.Tech Mechanical", "B.Tech Civil"]
        
        # Generate 50 Dummy Students
        for i in range(1, 51):
            u = Users(
                username=f"student_{i}_{fake.user_name()[:5]}", 
                pass_hash=generate_password_hash("password123"), 
                role="student", 
                profile_completed=True
            )
            db.session.add(u)
            db.session.flush()
            
            s = Student(
                user_id=u.id, 
                fname=fake.first_name(), 
                lname=fake.last_name(),
                roll=f"2023REG{1000+i}",  # CORRECT: Using 'roll' field
                email=fake.email(), 
                phone=fake.phone_number()[:15],
                cgpa=round(random.uniform(6.0, 9.9), 2), 
                graduation_year=random.choice([2025, 2026, 2027, 2028]),
                degree_field=random.choice(degree_options), 
                batch=random.choice([2021, 2022, 2023, 2024]),
                skills=", ".join(random.sample([
                    "Java", "C++", "Python", "Go", "Rust", "JavaScript", "TypeScript",
                    "React", "Vue", "Angular", "Node.js", "Django", "Flask",
                    "SQL", "MongoDB", "PostgreSQL", "Redis",
                    "AWS", "Azure", "GCP", "Docker", "Kubernetes",
                    "Machine Learning", "Deep Learning", "NLP", "Computer Vision"
                ], k=random.randint(3, 8))),
                bio=fake.paragraph(nb_sentences=4),  # Rich bio generated by Faker
                resume=f"http://127.0.0.1:5000/static/uploads/resumes/resume.pdf",
                github=f"https://github.com/{fake.user_name()}",
                linkedin=f"https://linkedin.com/in/{fake.user_name()}",
                portfolio=fake.url(),
                status=random.choice(['approved', 'approved', 'approved', 'approved', 'blacklisted'])  # 80% approved
            )
            db.session.add(s)
            all_students.append(s)

        # Generate 50 Dummy Companies
        industry_options = [
            "FinTech", "EdTech", "SaaS", "Cybersecurity", "HealthTech", 
            "E-Commerce", "Deep Learning", "Cloud Computing", "IoT", 
            "Blockchain", "Gaming", "AI/ML", "Data Analytics"
        ]
        
        employee_count_options = ["1-10", "10-50", "50-100", "100-500", "500-1000", "1000-5000", "5000+"]
        
        for i in range(1, 51):
            u = Users(
                username=f"company_{i}_{fake.user_name()[:5]}", 
                pass_hash=generate_password_hash("password123"), 
                role="company", 
                profile_completed=True
            )
            db.session.add(u)
            db.session.flush()
            
            c = Company(
                user_id=u.id, 
                name=fake.company(), 
                industry=random.choice(industry_options),
                logo="http://127.0.0.1:5000/static/uploads/logos/logo.png", 
                short_desc=fake.catch_phrase(),
                description=fake.text(max_nb_chars=600),  # Deep 600-character description
                location=f"{fake.city()}, {fake.country()}", 
                hr_contact=fake.name(), 
                email=fake.company_email(), 
                employees_count=random.choice(employee_count_options),  # CORRECT: Using 'employees_count'
                website=fake.url(), 
                status=random.choice(['approved', 'approved', 'approved', 'pending', 'rejected', 'blacklisted'])  # Mostly approved
            )
            db.session.add(c)
            all_companies.append(c)

        db.session.commit()

        print("Creating 60 highly detailed job drives...")
        job_titles = [
            "Software Development Engineer", 
            "Data Analyst Intern", 
            "Frontend Developer", 
            "Backend Engineer", 
            "Full Stack Developer",
            "Cloud Architect", 
            "Product Manager", 
            "Cybersecurity Analyst", 
            "Machine Learning Intern",
            "DevOps Engineer",
            "Mobile App Developer",
            "QA Engineer",
            "Business Analyst",
            "UI/UX Designer"
        ]
        
        all_drives = []
        approved_companies = [c for c in all_companies if c.status == 'approved']

        for _ in range(60):
            comp = random.choice(approved_companies)
            
            # Generating realistic, chunky requirements lists
            min_cgpa = round(random.uniform(6.5, 8.5), 1)
            primary_lang = random.choice(['Python', 'Java', 'C++', 'JavaScript', 'Go'])
            tech_stack = random.choice(['React', 'Node.js', 'Docker', 'Kubernetes', 'TensorFlow', 'Spring Boot', 'Django', 'Flutter'])
            
            reqs = (
                f"• Minimum {min_cgpa} CGPA required.\n"
                f"• Strong proficiency in {primary_lang} and object-oriented programming.\n"
                f"• Excellent understanding of Data Structures and Algorithms.\n"
                f"• Familiarity with {tech_stack} is highly preferred.\n"
                f"• Good communication skills and ability to work in teams.\n"
                f"• {fake.sentence()}"
            )

            drive = Drive(
                company_id=comp.id,
                title=random.choice(job_titles),
                description=fake.text(max_nb_chars=800),  # Huge job description
                requirements=reqs,
                package=round(random.uniform(4.0, 45.0), 2),  # LPA (Lakhs Per Annum)
                deadline=datetime.now().date() + timedelta(days=random.randint(-10, 90)),  # Some past, mostly future
                status=random.choice(['pending', 'approved', 'approved', 'approved', 'rejected', 'closed'])  # Mostly approved
            )
            db.session.add(drive)
            all_drives.append(drive)
        
        db.session.commit()

        print("Generating 200+ applications and pairing notifications...")
        approved_drives = [d for d in all_drives if d.status in ['approved', 'closed']]
        eligible_students = [s for s in all_students if s.status == 'approved']
        
        # FIXED: Using lowercase status values as per the model
        application_statuses = ['applied', 'shortlisted', 'rejected', 'selected']
        
        # Ensure our primary demo student has 10 applications for testing UI
        demo_student_drives = random.sample(approved_drives, min(10, len(approved_drives)))
        for drive in demo_student_drives:
            status = random.choice(application_statuses)
            db.session.add(Application(
                student_id=demo_student.id, 
                drive_id=drive.id, 
                status=status  # FIXED: lowercase status
            ))
            
            # Always give a notification to the demo student so the inbox isn't empty
            db.session.add(Notification(
                student_id=demo_student.id, 
                message=f"Application Update: Your application for '{drive.title}' at {drive.company_details.name} has been marked as '{status.capitalize()}'.",
                is_read=random.choice([True, False])
            ))

        # Generate massive amount of random applications
        combinations_used = set()
        applications_created = 0
        
        for _ in range(300):  # Attempt 300 random applications
            if applications_created >= 250:  # Stop at 250 successful applications
                break
                
            student = random.choice(eligible_students)
            drive = random.choice(approved_drives)
            
            if (student.id, drive.id) not in combinations_used:
                combinations_used.add((student.id, drive.id))
                
                status = random.choice(application_statuses)  # FIXED: lowercase status
                db.session.add(Application(
                    student_id=student.id, 
                    drive_id=drive.id, 
                    status=status
                ))
                
                # Add notification for the student (50% chance to avoid spam)
                if random.random() > 0.5:
                    db.session.add(Notification(
                        student_id=student.id, 
                        message=f"Update from {drive.company_details.name}: Your application for '{drive.title}' is currently marked as '{status.capitalize()}'.",
                        is_read=random.choice([True, False, False])  # More unread notifications
                    ))
                
                applications_created += 1

        db.session.commit()
        
        # ==========================================
        # SUCCESS OUTPUT
        # ==========================================

        print("\n--- SEEDING COMPLETE ---")
        print()
        print("📊 DATABASE STATISTICS:")
        print()
        print(f"👥 Users created:           {Users.query.count()}")
        print(f"🎓 Students created:        {Student.query.count()}")
        print(f"🏢 Companies created:       {Company.query.count()}")
        print(f"💼 Drives created:          {Drive.query.count()}")
        print(f"📄 Applications created:    {Application.query.count()}")
        print(f"🔔 Notifications generated: {Notification.query.count()}")
        print()
        print("🔐 LOGIN CREDENTIALS:")
        print()
        print("ADMIN    → username: admin    | password: admin")
        print("STUDENT  → username: student  | password: student")
        print("COMPANY  → username: company  | password: company")
        print()
        print("TIP: Other accounts use 'password123' as password")
        print()
        
        # Additional useful info
        print("\nDETAILED BREAKDOWN:")
        print()
        print(f"Approved Companies:    {Company.query.filter_by(status='approved').count()}")
        print(f"Pending Companies:     {Company.query.filter_by(status='pending').count()}")
        print(f"Rejected Companies:    {Company.query.filter_by(status='rejected').count()}")
        print(f"Blacklisted Companies: {Company.query.filter_by(status='blacklisted').count()}")
        print()
        print(f"Approved Students:     {Student.query.filter_by(status='approved').count()}")
        print(f"Blacklisted Students:  {Student.query.filter_by(status='blacklisted').count()}")
        print()
        print(f"Approved Drives:       {Drive.query.filter_by(status='approved').count()}")
        print(f"Pending Drives:        {Drive.query.filter_by(status='pending').count()}")
        print(f"Rejected Drives:       {Drive.query.filter_by(status='rejected').count()}")
        print(f"Closed Drives:         {Drive.query.filter_by(status='closed').count()}")
        print()
        print(f"Applied:               {Application.query.filter_by(status='applied').count()}")
        print(f"Shortlisted:           {Application.query.filter_by(status='shortlisted').count()}")
        print(f"Selected:              {Application.query.filter_by(status='selected').count()}")
        print(f"Rejected:              {Application.query.filter_by(status='rejected').count()}")
        print()
        print("\nDatabase is ready for testing!\n")

if __name__ == "__main__":
    seed_data()